### ISSUE TITLE
Authenticate issue with LLS 

### ISSUE THREAD

**Issue by max-macstadium** [teradici/pcoip-license-server#7]
Trying to use the new fork (individual-license) and having issues with the authentication. It seems to be in the /libs/ls.py file. Getting authentication issues. Have verified username, password and URI work as expected with older version of script. Getting this error: 
Traceback (most recent call last):
  File "pcoip-agent-ls.py", line 272, in <module>
    client = LSClient(uri, args.ls_username, args.ls_password)
  File "/home/msadmin/teradici/pcoip-license-server-individual-licenses/libs/ls.py", line 45, in __init__
    self.authenticate()
  File "/home/msadmin/teradici/pcoip-license-server-individual-licenses/libs/ls.py", line 64, in authenticate
    raise Exception(msg)
Exception: Authentication Error: Response code: 500. Please verify ls url or cls id, username and password and try again.

Tried reviewing ls.py file but could not follow what changes were made. This is for a local license server and not the cloud registration ID.

**Comment by ppavlik** [comment]
We are looking into this issue.
